// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicWorkItem,
  DefaultWorkItemProps
} from "./plasmic/blank_project/PlasmicWorkItem";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import gsap from "gsap/all";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface WorkItemProps extends Omit<DefaultWorkItemProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultWorkItemProps altogether and have
// total control over the props for your component.
interface WorkItemProps extends DefaultWorkItemProps {}

function WorkItem_(props: WorkItemProps, ref: HTMLElementRefOf<"div">) {
    let componentRef = React.useRef<HTMLDivElement>(null);
    let dom: HTMLDivElement | null;

    React.useEffect(() => {
      dom = componentRef.current;
      if(!dom) return;

      let image = dom.querySelector("#image") as HTMLImageElement;
      gsap.from(image, {duration: 1, opacity: 0, scale: 0.8});

      let headline = dom.querySelector('#headline') as HTMLElement;
      gsap.from(headline, {duration: 1, opacity: 0, y: "-10"});

      let description = dom.querySelector('#description') as HTMLElement;
      gsap.from(description, {duration: 1, opacity: 0, x: "-20"});

    });
    
    return (
      <div ref={componentRef}>
        <PlasmicWorkItem root={{ ref }} {...props} />
      </div>
    )
}

const WorkItem = React.forwardRef(WorkItem_);
export default WorkItem;
